# Generated by Django 4.2.6 on 2023-10-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.CharField(max_length=250)),
                ('dest_image', models.ImageField(upload_to='pics')),
                ('dest_description', models.TextField()),
            ],
        ),
    ]
